version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./app
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge